//SETTINGS
export const SET_OPTION = 'SET_OPTION';
export const SET_INTEGRATION = 'SET_INTEGRATION';
export const SETTINGS_SAVING = 'SETTINGS_SAVING';
export const SETTINGS_SAVED = 'SETTINGS_SAVED';
export const SETTINGS_DONE = 'SETTINGS_DONE';
export const SET_INTEGRATION_DETAILS = 'SET_INTEGRATION_DETAILS';

//GENERAL SETTINGS
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const SAVE_SETTINGS = 'SAVE_SETTINGS';

//Notices
export const ADD_NOTICE = 'ADD_NOTICE';
export const REMOVE_NOTICE = 'REMOVE_NOTICE';
export const REMOVE_SIMILAR_NOTICES = 'REMOVE_SIMILAR_NOTICES';

//entries - PLURAL
export const ENTRIES_FETCHING = 'ENTRIES_FETCHING';
export const ENTRIES_FETCHED = 'ENTRIES_FETCHED';
export const ENTRIES_FETCH_FAILED = 'ENTRIES_FETCH_FAILED';
export const SET_ENTRIES_REFETCHING_STATUS = 'SET_ENTRIES_REFETCHING_STATUS';

// entry - SINGULAR
export const UPDATE_ENTRY = 'UPDATE_ENTRY';
